// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHQIVaIdcxWE9UEnh3QxR4WOA8hrbXcpU',
    appId: '1:74029902960:web:a5815856c82c87171498b5',
    messagingSenderId: '74029902960',
    projectId: 'smart-meal-planner-3d97f',
    authDomain: 'smart-meal-planner-3d97f.firebaseapp.com',
    storageBucket: 'smart-meal-planner-3d97f.firebasestorage.app',
    measurementId: 'G-7YM1JZL2KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMLW8t8G8mLKg8Cw_ariV03e0kschzVso',
    appId: '1:74029902960:android:33c590791af58f731498b5',
    messagingSenderId: '74029902960',
    projectId: 'smart-meal-planner-3d97f',
    storageBucket: 'smart-meal-planner-3d97f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7vR7cXUIqGk_jc5DVGvJIyOVQpb1iRSw',
    appId: '1:74029902960:ios:597703c2fe579aff1498b5',
    messagingSenderId: '74029902960',
    projectId: 'smart-meal-planner-3d97f',
    storageBucket: 'smart-meal-planner-3d97f.firebasestorage.app',
    iosBundleId: 'com.example.smartMealPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7vR7cXUIqGk_jc5DVGvJIyOVQpb1iRSw',
    appId: '1:74029902960:ios:597703c2fe579aff1498b5',
    messagingSenderId: '74029902960',
    projectId: 'smart-meal-planner-3d97f',
    storageBucket: 'smart-meal-planner-3d97f.firebasestorage.app',
    iosBundleId: 'com.example.smartMealPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHQIVaIdcxWE9UEnh3QxR4WOA8hrbXcpU',
    appId: '1:74029902960:web:4c1e73ee06000b8a1498b5',
    messagingSenderId: '74029902960',
    projectId: 'smart-meal-planner-3d97f',
    authDomain: 'smart-meal-planner-3d97f.firebaseapp.com',
    storageBucket: 'smart-meal-planner-3d97f.firebasestorage.app',
    measurementId: 'G-LYL6ZY8YQN',
  );
}
